# -------------------------------
# docker-compose.yml (con db-postgres)
# -------------------------------
version: '3'
services:
  registry-api:
    build: ./registry-api
    ports:
      - "8000:8000"
  access-control:
    build: ./access-control
    ports:
      - "8001:8000"
  data-store:
    build: ./data-store
    depends_on:
      - db-postgres
  db-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: registrydb
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@i-phoqs.it
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5050:80"
    depends_on:
      - db-postgres
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  pgdata:
  pgadmin_data: